"""Agregando columna virtual_tour_url a listings

Revision ID: 44389d15dbcb
Revises: d538ac0b28ea
Create Date: 2026-02-21 15:58:51.528740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44389d15dbcb'
down_revision = 'd538ac0b28ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('virtual_tour_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('virtual_tour_url')

    # ### end Alembic commands ###
