"""Agregando paquetes tier y expiracion a listings

Revision ID: 9bebc16335b4
Revises: 60266e522f9a
Create Date: 2026-02-21 06:30:43.297982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bebc16335b4'
down_revision = '60266e522f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('duration_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('expires_at')
        batch_op.drop_column('duration_days')
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
