"""Agregar sistema de creditos

Revision ID: d538ac0b28ea
Revises: 9bebc16335b4
Create Date: 2026-02-21 15:23:03.370444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd538ac0b28ea'
down_revision = '9bebc16335b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_sales', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('package_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('prof_credits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prem_credits', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('prem_credits')
        batch_op.drop_column('prof_credits')
        batch_op.drop_column('package_name')
        batch_op.drop_column('total_sales')

    # ### end Alembic commands ###
